### PR TITLE
Refactoring to make code more reactive and modular

### PR DESCRIPTION
**Pull request by d3vel0per**
After hearing complains about `.block()` decided to give reactive code a shot and additional changes to add more structure

Other misc. changes:
1. `/tophelpers` param is optional(default 10, max 20)
2. `^process` commands second param is optional. If unspecified is assumed to the ending line number

### CODE REVIEW

**Comment by d3vel0per** [comment]
This build is dockerized now.

Run `gradlew jibDockerBuild` to generate a local image
`docker images` should show an entry for `togetherjava/tjbot`
```
REPOSITORY                                                  TAG                                                     IMAGE ID       CREATED         SIZE
adoptopenjdk/openjdk16                                      alpine-slim                                             e61116c88534   2 weeks ago     285MB
togetherjava/tjbot                                          1.0                                                     c7a3db666815   51 years ago    308MB
```

To run in ephemeral mode ie. temporary persistence, its just:
`docker run togetherjava/tjbot:1.0 <bot_token>`

while to have the database hosted outside once can run:
`docker run -v <your_local_dir>:/var/tjbot togetherjava/tjbot:1.0 BOT_TOKEN`

To stop the container, run a:
`docker container ls` and you should see an output like:
```
CONTAINER ID   IMAGE                    COMMAND                  CREATED          STATUS          PORTS     NAMES
096b1704256a   togetherjava/tjbot:1.0   "java --enable-previ…"   2 minutes ago    Up 2 minutes              jolly_hypatia
f9712bedc707   2e8bebac9f37             "contour serve --inc…"   39 minutes ago   Up 39 minutes             k8s_contour_contour-6648989f79-w4wlc_projectcontour_9304252a-7d4e-4343-9a8b-82f90b2c05ca_4
```
and follow it up with
`docker stop <container_id>`

**Comment by illuminator3** [comment]
I've made a big commit fixing the code style of the code base, this will conflict with your changes

**Comment by d3vel0per** [comment]
> I've made a big commit fixing the code style of the code base, this will conflict with your changes

Ok. Let's keep this on hold till I merge back or put in equivalents.
Weekdays start so I will try to check once work hours are over.

**Comment by d3vel0per** [comment]
Closing this one for updated PR #29

**Pull request closed without merging**
